### ISSUE TITLE
Confusing result

### ISSUE THREAD

**Issue by Rose1917** [matszpk/cnfgen#1]
First, thanks for your great job. 

It seems that the result cnf will contains more variables than I defined.
Take the code snippet in documentation for example:
Src Code:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/49433992/206541986-619448c7-4c24-401f-80d9-0eedd1b9eb3a.png">
Output:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/49433992/206541873-48003e63-fec1-4e25-b661-e5f49d733d48.png">

I defined four variables but the cnf contains 7 variables. 
For some purpose, I want to relocate the variable in the cnf later. So I want to identify the input variables also.

If making the output only contains 4 variables is possible?

**Comment by matszpk** [comment]
Output is correct. These additional variables just hold subexpressions results.
Number of variable can be get by using `varlit` method from variable literal (normal or negated variable number) - if it really is variable then this method will returns Some(varlit).
